#!/bin/bash

#nfs install centos7 server -- run as root

#allow services through the firewall
firewall-cmd --permanent --zone=public --add-service=nfs
firewall-cmd --reload

#install nfs
yum -y install nfs-utils

#start nfs server and services
systemctl enable nfs-server.service
systemctl start nfs-server.service
#systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmapd
systemctl enable rpcbind
systemctl start rpcbind
systemctl start nfs-lock
systemctl start nfs-idmap


#make directories and adjust ownership and permissions
mkdir /var/dev
chown nfsnobody:nfsnobody /var/dev
chmod 755 /var/dev

mkdir /var/config
chown nfsnobody:nfsnobody /var/config
chmod 755 /var/config

#adjust /etc/exports to allow sharing of folders ***must use internal IPs***
#vi /etc/exports
#add these lines       ***use sed--add uncommented lines-empty file***
echo "/home    *(rw,sync,no_all_squash)
/var/dev       *(rw,sync,no_all_squash)
/var/config    *(rw,sync,no_all_squash)" >> /etc/exports     



#make changes take effect
exportfs -a
systemctl restart nfs-server

#this is my monitoring and trending script

    myusername="ashand01"                         # set this to your username
    mynagiosserver="nagios-a"                     # set this to your nagios server name
    mycactiserver="cacti-server"                      # set this to your cacti server
    myreposerver="yumrepo-server"                       # set this to your repo server
    mynagiosserverip="146.148.42.252"                   # set this to the ip address of your nagios server

    generate_config.sh $1 $2              # code I gave you in a previous assignment that generates a nagios config

    gcloud compute copy-files $1.cfg $myusername@$mynagiosserver:/etc/nagios/conf.d

                                      # note: I had to add user my gcloud user to group nagios using usermod -a -G nagios 
    $myusername on my nagios server in order to make this work.
                                      # I also had to chmod 770 /etc/nagios/conf.d

    configstatus=$( \
    gcloud compute ssh $myusername@$mynagiosserver \
    "sudo /usr/sbin/nagios -v /etc/nagios/nagios.cfg" \
    | grep "Things look okay - No serious problems" \
    )

    if [[ $configstatus ]]; then 
    gcloud compute ssh $myusername@$mynagiosserver "sudo systemctl restart nagios"
    echo "$1 has been added to nagios."
    else
    echo "There was a problem with the nagios config, please log into $mynagiosserver and run /usr/sbin/nagios -v 
    /etc/nagios/nagios.cfg to figure out where the problem is"; 
    exit 1;
    fi

    # (I'll throw the cacti code in here in a bit)

