#!/bin/bash

#rsyslog server side install script -- run as root on centos7 server

#adjust rsyslog.conf to listen for tcp, udp communication

sed -ie 's/#$ModLoad imudp/$ModLoad imudp/g' /etc/rsyslog.conf

sed -ie 's/#$UDPServerRun 514/$UDPServerRun 514/g' /etc/rsyslog.conf

sed -ie 's/#$ModLoad imtcp/$ModLoad imtcp/g' /etc/rsyslog.conf

sed -ie 's/#$InputTCPServerRun 514/$InputTCPServerRun 514/g' /etc/rsyslog.conf

#restart the rsyslog service

systemctl restart rsyslog.service

#open firewall port 514 to allow tcp, udp communication

firewall-cmd --permanent --zone=public --add-port=514/tcp
firewall-cmd --permanent --zone=public --add-port=514/udp
firewall-cmd --reload

#confirm server listening on port 514

yum -y install net-tools
netstat -antup | grep 514

#this is my monitoring and trending script

    myusername="ashand01"                         # set this to your username
    mynagiosserver="nagios-a"                     # set this to your nagios server name
    mycactiserver="cacti-server"                      # set this to your cacti server
    myreposerver="yumrepo-server"                       # set this to your repo server
    mynagiosserverip="146.148.42.252"                   # set this to the ip address of your nagios server

    generate_config.sh $1 $2              # code I gave you in a previous assignment that generates a nagios config

    gcloud compute copy-files $1.cfg $myusername@$mynagiosserver:/etc/nagios/conf.d

                                      # note: I had to add user my gcloud user to group nagios using usermod -a -G nagios 
    $myusername on my nagios server in order to make this work.
                                      # I also had to chmod 770 /etc/nagios/conf.d

    configstatus=$( \
    gcloud compute ssh $myusername@$mynagiosserver \
    "sudo /usr/sbin/nagios -v /etc/nagios/nagios.cfg" \
    | grep "Things look okay - No serious problems" \
    )

    if [[ $configstatus ]]; then 
    gcloud compute ssh $myusername@$mynagiosserver "sudo systemctl restart nagios"
    echo "$1 has been added to nagios."
    else
    echo "There was a problem with the nagios config, please log into $mynagiosserver and run /usr/sbin/nagios -v 
    /etc/nagios/nagios.cfg to figure out where the problem is"; 
    exit 1;
    fi

    # (I'll throw the cacti code in here in a bit)
